title: Weather App Homepage
page-top-title: CSCE 625 Artificial Intelligence
top-section-bg-text: Agentic AI Weather Emergency Response System
home-subtitle: INTRODUCTION
copyright-text: '&copy; Sai Kiran Dyavadi | Sirisha NK | Rishitha Nimma 2025-2026. All Rights Reserved.'
